on:
    push:
        jobs:
            lint:
                runs-on: ubuntu-latest

                steps:
                    - name: Checkout code
                      uses: actions/checkout@v4

                    - name: Setup Node.js
                      uses: actions/setup-node@v4
                      with:
                        node-version: 20

                    - name: Install dependencies
                      run: npm install

                    - name: Check code quality
                      run: npm run lint


            test:
                runs-on: ubuntu-latest

                steps:
                    - name: Checkout code
                      uses: actions/checkout@v4

                    - name: Setup Node.js
                      uses: actions/setup-node@v4
                      with:
                        node-version: 20

                    - name: Install dependencies
                      run: npm install

                    - name: run tests
                      run: npm test


            summary:
                runs-on: ubuntu-latest
                needs: [lint, test]

                steps:
                    - name: Who activated the pipeline
                      run: echo "Pipeline triggered by: ${{ github.actor }}"

                    - name: lint results
                      run: echo "Lint results: ${{ needs.lint.result }}"

                    - name: Test results
                      run: echo "Test results: ${{ needs.test.result }}"


